# Generated by Django 3.0.5 on 2020-05-11 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpg', '0002_auto_20200511_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price_info',
            old_name='date',
            new_name='dates',
        ),
    ]
